---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:4.4  # Corrected indentation
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data/db     # Container mount path
          name: mongo-data        # Volume name, must match the name defined below
      volumes:
      - name: mongo-data                # Volume name
        hostPath:
          path: /data/mongo-data        # Node path
          type: DirectoryOrCreate       # Points to a directory, creates it if it doesn't exist
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: ClusterIP  # Removed duplicate fields
